baseURL = '/'
languageCode = 'en-us'
title = 'MathBlog'
# theme = "hyde"
theme = "hyde-dev"
# theme = "hugo-theme-pure"
publishdir = "docs"
paginate = 2
[Menus]
  main = [
    #   {Name = "Github", URL = "https://github.com/username/"},
    #   {Name = "LinkedIn", URL = "https://www.linkedin.com/in/username/"}
    {Name="post",URL="/post"},
    {Name="math",URL="/math"},
  ]
[params]
  thh = "thh-value"
#   themeColor = "theme-base-08"
#   themeColor = "theme-base-09"
#   themeColor = "theme-base-0a"
#   themeColor = "theme-base-0b"
#   themeColor = "theme-base-0c"
  themeColor = "theme-base-0d"
#   themeColor = "theme-base-0e"
#   themeColor = "theme-base-0f"
  layoutReverse = true
  enableMathJax = true #Enable mathjax support, to use mathematical notations
